#!/bin/bash --login

#SBATCH --job-name=ufetContraExp

#SBATCH --output=logs/ufet_exp/contra_cnetp_vocab_pt_conceptfix_contra_bertlarge_cnetpchatgpt100k_model/out_compli_cluster_exp_contra_bert_large_cnetp_vocab.txt
#SBATCH --error=logs/ufet_exp/contra_cnetp_vocab_pt_conceptfix_contra_bertlarge_cnetpchatgpt100k_model/err_compli_cluster_exp_contra_bert_large_cnetp_vocab.txt

#SBATCH --tasks-per-node=5
#SBATCH --ntasks=5
#SBATCH -A scw1858

#SBATCH -p gpu_v100,gpu
#SBATCH --gres=gpu:1

#SBATCH --mem=16G
#SBATCH -t 0-8:00:00

conda activate venv

python3 get_property_similar_concepts.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/contra_cnetp_vocab_pt_conceptfix_contra_bertlarge_cnetpchatgpt100k_model/5_complementary_clusters_debv3l_filterthresh50.json
python3 get_property_similar_concepts.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/contra_cnetp_vocab_pt_conceptfix_contra_bertlarge_cnetpchatgpt100k_model/5_complementary_clusters_debv3l_filterthresh75.json
python3 je_filter_similar_props.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/contra_cnetp_vocab_pt_conceptfix_contra_bertlarge_cnetpchatgpt100k_model/6_mcrae_cslb_deb3l_filter_prop_sim_50cons_filterthresh50.json
python3 je_filter_similar_props.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/contra_cnetp_vocab_pt_conceptfix_contra_bertlarge_cnetpchatgpt100k_model/6_mcrae_cslb_deb3l_filter_prop_sim_50cons_filterthresh75.json

echo 'Job Finished !!!'
