#!/bin/bash --login

#SBATCH --job-name=ufetChatGpt100k_vocab

#SBATCH --output=logs/ufet_exp/chatgpt100k_vocab_chatgpt100k_bienc/out_get_clusters.txt
#SBATCH --error=logs/ufet_exp/chatgpt100k_vocab_chatgpt100k_bienc/err_get_clusters.txt

#SBATCH --tasks-per-node=5
#SBATCH --ntasks=5
#SBATCH -A scw1858

#SBATCH -p gpu_v100,gpu
#SBATCH --gres=gpu:1

#SBATCH --mem=16G
#SBATCH -t 0-10:00:00

conda activate venv


python3 get_embeds_and_train_data.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/1_ufettype_embed.json
python3 get_embeds_and_train_data.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/2_chatgpt100k_vocab_embeds.json
python3 get_embeds_and_train_data.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/3_ufet_type_similar_50chatgpt100k_props.json

python3 je_filter_similar_props.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/4_mcrae_cslb_deb3l_filter_con_sim_50props_filterthresh50_75_90.json


python3 get_property_similar_concepts.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/5_get_prop_similar50types_filterthresh50.json
python3 get_property_similar_concepts.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/5_get_prop_similar50types_filterthresh75.json
python3 get_property_similar_concepts.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/5_get_prop_similar50types_filterthresh90.json

python3 je_filter_similar_props.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/6_mcrae_cslb_deb3l_filter_prop_sim_50cons_filterthresh50.json
python3 je_filter_similar_props.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/6_mcrae_cslb_deb3l_filter_prop_sim_50cons_filterthresh75.json
python3 je_filter_similar_props.py --config_file configs/2_configs_get_embeds_and_train_data/ufet/chatgpt100k_vocab_chatgpt100k_bienc/6_mcrae_cslb_deb3l_filter_prop_sim_50cons_filterthresh90.json

echo 'Job Finished !!!'
